version: '3.1'

services:

  frontend:
    image: application--frontend
    networks:
     - cicdapp
    ports:
     - 80:80
    container_name: app-frontend
    restart: unless-stopped

networks:
  cicdapp:
